spring.application.name=PRODUCT-SERVICE
#server.port=9091

# Spring Boot Admin
spring.boot.admin.client.url=http://localhost:1111
spring.boot.admin.client.instance.service-base-url=http://localhost:${server.port}

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address=true
#eureka.instance.prefer-ip-address=false
